version: "3.9"
services:
# note remove arm64v8 if not using on raspberry pi
  db:
    image: docker.io/arm64v8/postgres:16-alpine3.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 0s
      timeout: 10s
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # change your db info here
      POSTGRES_DB: db
      POSTGRES_USER: picture_user
      POSTGRES_PASSWORD: picture_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/www/storage/:/var/lib/postgresql/storage

  nginx:
    image: docker.io/arm64v8/nginx:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://homeserver/login"]
      interval: 0s
      timeout: 10s
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/www/pictures/html:/usr/share/nginx/html
      - /srv/picture-api/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/storage/:/usr/share/nginx/storage
    depends_on:
      - db

  api:
    image: api:latest
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://homeserver:8080/api/v1/health/ping" ]
      interval: 0s
      timeout: 10s
    restart: always
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - /var/www/storage/:/app/storage
    depends_on:
      - nginx

volumes:
  pgdata:

